---
#https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#ansible-collections-ansible-posix-synchronize-module

- name: Synchronize Puzzle Massive resources directory from local
  hosts: legacy_puzzle_massive
  remote_user: dev
  become: true
  tasks:

    - name: Synchronize resources directory from local
      ansible.posix.synchronize:
        src: "{{ resources_directory }}"
        dest: /srv/puzzle-massive/
    - name: Set permissions
      ansible.builtin.file:
        path: "/srv/puzzle-massive/resources"
        owner: dev
        group: dev
        recurse: yes
        state: directory
